package chart

import (
	"bytes"
	"encoding/json"
	"flag"
	"math"
	"os"
	"path/filepath"
	"testing"
	"time"

	job "github.com/bensyverson/jobs/internal/job"
)

// The chart panel's enhancement script redraws the burn-up in the
// browser (decision 9 of project/2026-09-27-chart-panel-revision.md),
// so the JS path builders in internal/web/assets/js/chart-geometry.mjs
// must draw exactly what LayoutBurnup draws. This test writes the
// shared fixture — islands and the paths Go laid out for them — and
// fails when the checked-in copy is stale; the node suite
// (internal/web/jstest/chart-geometry.test.mjs) asserts the JS builders
// reproduce every path from the island alone.

var updateFixtures = flag.Bool("update", false, "rewrite internal/web/jstest/fixtures from the Go layout")

const geometryFixturePath = "../jstest/fixtures/burnup-geometry.json"

// geometryFixture is the file both suites read.
type geometryFixture struct {
	Note    string         `json:"note"`
	Numbers []numberCase   `json:"numbers"`
	Cases   []geometryCase `json:"cases"`
}

// numberCase is one viewBox coordinate and how fmtNum spells it —
// half-way ties included, where JavaScript's toFixed and Go's
// strconv round differently.
type numberCase struct {
	In  float64 `json:"in"`
	Out string  `json:"out"`
}

// geometryCase is one island and everything LayoutBurnup drew for it
// that the script redraws: the five paths, the end dots and the end
// labels' heights.
type geometryCase struct {
	Name     string     `json:"name"`
	Island   PanelData  `json:"island"`
	Scope    string     `json:"scopePath"`
	Done     string     `json:"donePath"`
	Gap      string     `json:"gapPath"`
	Blocked  string     `json:"blockedPath"`
	Canceled string     `json:"canceledPath"`
	ScopeDot fixturePos `json:"scopeDot"`
	DoneDot  fixturePos `json:"doneDot"`
	CreatedY string     `json:"createdY"`
	DoneY    string     `json:"doneY"`
}

type fixturePos struct {
	X string `json:"x"`
	Y string `json:"y"`
}

// fixtureReports are the windows the fixture pins: a band and a
// blocked share, a flat window, a dense irregular trace on an
// unaligned window, and lines that end close together near the top.
func fixtureReports() []struct {
	name string
	rep  job.Report
} {
	wob := func(i int) float64 { return (math.Sin(float64(i)*1.7)+math.Sin(float64(i)*0.63))/4 + 0.5 }

	ramp := hourly(40, func(i int) job.Sample {
		canceled := 3
		if i > 20 {
			canceled += (i - 20) / 2
		}
		return job.Sample{Scope: 50 + i - max(0, i-20)/2, Done: i, Blocked: i % 5, Canceled: canceled}
	})
	ramp.Activity = []job.ActivityCount{
		{Start: t0, End: t0.Add(20 * time.Hour), Created: 20, Claimed: 9, Done: 20, Blocked: 3},
		{Start: t0.Add(20 * time.Hour), End: t0.Add(40 * time.Hour), Created: 10, Claimed: 4, Done: 20, Blocked: 1},
	}
	ramp.Leaves = job.LeafFigures{Created: 30, Done: 40, Canceled: 10}

	flat := hourly(12, func(int) job.Sample { return job.Sample{Scope: 402, Done: 402} })

	// 300 samples every 29 minutes from an unaligned Since, so x lands
	// on long fractions; a reopen dip at 150.
	since := t0.Add(7*time.Minute + 13*time.Second)
	dense := job.Report{Schema: job.ReportSchema}
	for i := range 300 {
		done := 380 + i/12
		if i >= 150 && i < 160 {
			done -= 6
		}
		scope := 400 + int(20*wob(i)) + i/20
		dense.Trace = append(dense.Trace, job.Sample{
			End: since.Add(time.Duration(i) * 29 * time.Minute), Scope: scope, Done: min(done, scope),
			Blocked: int(4 * wob(i+3)), Canceled: 7 + i/40,
		})
	}
	dense.Window = job.ReportWindow{Since: since, Until: dense.Trace[299].End, Bucket: job.BucketDay, Timezone: "UTC"}

	closeEnds := hourly(9, func(i int) job.Sample { return job.Sample{Scope: 10 + i, Done: 8 + i, Blocked: 1} })

	return []struct {
		name string
		rep  job.Report
	}{{"ramp-with-band", ramp}, {"flat", flat}, {"dense-unaligned", dense}, {"close-ends", closeEnds}}
}

func buildGeometryFixture() geometryFixture {
	f := geometryFixture{
		Note: "Generated by TestBurnupGeometryFixture (internal/web/chart). Do not edit: run go test ./internal/web/chart -run TestBurnupGeometryFixture -update.",
	}
	for _, in := range []float64{0, 1000, 0.125, 0.375, 0.625, 0.875, 1.125, 2.5, 1.005, 2.675, 999.995,
		-0.001, -0.125, -0.375, 12.345, 0.0049999, 1e-10, 1000.0 / 3, 2000.0 / 3, 66.66666666666667, 83.33} {
		f.Numbers = append(f.Numbers, numberCase{In: in, Out: fmtNum(in)})
	}
	for _, c := range fixtureReports() {
		b := LayoutBurnup(c.rep, time.UTC)
		f.Cases = append(f.Cases, geometryCase{
			Name: c.name, Island: LayoutPanelData(c.rep, b, LayoutActivity(c.rep, time.UTC)),
			Scope: b.ScopePath, Done: b.DonePath, Gap: b.GapPath, Blocked: b.BlockedPath, Canceled: b.CanceledPath,
			ScopeDot: fixturePos{b.ScopeDot.X, b.ScopeDot.Y}, DoneDot: fixturePos{b.DoneDot.X, b.DoneDot.Y},
			CreatedY: b.Created.Y, DoneY: b.Done.Y,
		})
	}
	return f
}

// TestBurnupGeometryFixture fails when the checked-in fixture no longer
// matches the Go layout, so the JS geometry cannot drift from it
// silently: a Go change that moves a path has to regenerate the file,
// and then the node suite holds the JS to it.
func TestBurnupGeometryFixture(t *testing.T) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	if err := enc.Encode(buildGeometryFixture()); err != nil {
		t.Fatal(err)
	}
	path := filepath.FromSlash(geometryFixturePath)
	if *updateFixtures {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (run go test ./internal/web/chart -run TestBurnupGeometryFixture -update)", path, err)
	}
	if !bytes.Equal(got, buf.Bytes()) {
		t.Fatalf("%s is stale: the Go burn-up layout changed. Regenerate it with\n  go test ./internal/web/chart -run TestBurnupGeometryFixture -update\nthen run make test-js so the JS geometry is held to the new paths.", path)
	}
}
